### ISSUE TITLE
a bug in electronegativity calculation...

### ISSUE THREAD

**Issue by usccolumbia** [WMD-group/SMACT#35]
I tried to enumerate all compositions for element set Sr Ti O
got the error below.      the sum(stoichioetries) ==0 which is impossible

rqworker_1  | 3 ['Sr', 'Ti', 'O']
rqworker_1  | [(('Sr', 'Ti', 'O'), (1, -1, -2), (3, 1, 1)), (('Sr', 'Ti', 'O'), (1, -1, -2), (4, 2, 1)), (('Sr', 'Ti', 'O'), (1, -1, -1), (2, 1, 1)), (('Sr', 'Ti', 'O'), (1, -1, -1), (3, 1, 2)), (('Sr', 'Ti', 'O'), (1, -1, -1), (3, 2, 1)), (('Sr', 'Ti', 'O'), (1, -1, -1), (4, 1, 3)), (('Sr', 'Ti', 'O'), (1, -1, -1), (4, 3, 1)), (('Sr', 'Ti', 'O'), (1, 1, -2), (1, 1, 1)), (('Sr', 'Ti', 'O'), (1, 1, -2), (1, 3, 2)), (('Sr', 'Ti', 'O'), (1, 1, -2), (2, 4, 3)), (('Sr', 'Ti', 'O'), (1, 1, -2), (3, 1, 2)), (('Sr', 'Ti', 'O'), (1, 1, -2), (4, 2, 3)), (('Sr', 'Ti', 'O'), (1, 1, -1), (1, 1, 2)), (('Sr', 'Ti', 'O'), (1, 1, -1), (1, 2, 3)), (('Sr', 'Ti', 'O'), (1, 1, -1), (1, 3, 4)), (('Sr', 'Ti', 'O'), (1, 1, -1), (2, 1, 3)), (('Sr', 'Ti', 'O'), (1, 1, -1), (3, 1, 4)), (('Sr', 'Ti', 'O'), (1, 2, -2), (2, 1, 2)), (('Sr', 'Ti', 'O'), (1, 2, -2), (2, 2, 3)), (('Sr', 'Ti', 'O'), (1, 2, -2), (2, 3, 4)), (('Sr', 'Ti', 'O'), (1, 2, -2), (4, 1, 3)), (('Sr', 'Ti', 'O'), (1, 2, -1), (1, 1, 3)), (('Sr', 'Ti', 'O'), (1, 2, -1), (2, 1, 4)), (('Sr', 'Ti', 'O'), (1, 3, -2), (1, 1, 2)), (('Sr', 'Ti', 'O'), (1, 3, -2), (3, 1, 3)), (('Sr', 'Ti', 'O'), (1, 3, -1), (1, 1, 4)), (('Sr', 'Ti', 'O'), (1, 4, -2), (2, 1, 3)), (('Sr', 'Ti', 'O'), (1, 4, -2), (4, 1, 4)), (('Sr', 'Ti', 'O'), (2, -1, -2), (2, 2, 1)), (('Sr', 'Ti', 'O'), (2, -1, -2), (3, 2, 2)), (('Sr', 'Ti', 'O'), (2, -1, -2), (3, 4, 1)), (('Sr', 'Ti', 'O'), (2, -1, -2), (4, 2, 3)), (('Sr', 'Ti', 'O'), (2, -1, -1), (1, 1, 1)), (('Sr', 'Ti', 'O'), (2, -1, -1), (2, 1, 3)), (('Sr', 'Ti', 'O'), (2, -1, -1), (2, 3, 1)), (('Sr', 'Ti', 'O'), (2, -1, -1), (3, 2, 4)), (('Sr', 'Ti', 'O'), (2, -1, -1), (3, 4, 2)), (('Sr', 'Ti', 'O'), (2, 1, -2), (1, 2, 2)), (('Sr', 'Ti', 'O'), (2, 1, -2), (1, 4, 3)), (('Sr', 'Ti', 'O'), (2, 1, -2), (2, 2, 3)), (('Sr', 'Ti', 'O'), (2, 1, -2), (3, 2, 4)), (('Sr', 'Ti', 'O'), (2, 1, -1), (1, 1, 3)), (('Sr', 'Ti', 'O'), (2, 1, -1), (1, 2, 4)), (('Sr', 'Ti', 'O'), (2, 2, -2), (1, 1, 2)), (('Sr', 'Ti', 'O'), (2, 2, -2), (1, 2, 3)), (('Sr', 'Ti', 'O'), (2, 2, -2), (1, 3, 4)), (('Sr', 'Ti', 'O'), (2, 2, -2), (2, 1, 3)), (('Sr', 'Ti', 'O'), (2, 2, -2), (3, 1, 4)), (('Sr', 'Ti', 'O'), (2, 2, -1), (1, 1, 4)), (('Sr', 'Ti', 'O'), (2, 3, -2), (1, 2, 4)), (('Sr', 'Ti', 'O'), (2, 4, -2), (1, 1, 3)), (('Sr', 'Ti', 'O'), (2, 4, -2), (2, 1, 4))]
rqworker_1  | Traceback (most recent call last):
rqworker_1  |   File "/code/app/views/base.py", line 147, in run
rqworker_1  |     result = agent.work()
rqworker_1  |   File "/code/app/views/compositionexplore/Compositionexplore.py", line 128, in work
rqworker_1  |     output,resultfile = enumerate_compositions(elements)
rqworker_1  |   File "/code/app/views/compositionexplore/Compositionexplore.py", line 54, in enumerate_compositions
rqworker_1  |     a in allowed_combinations]
rqworker_1  |   File "/code/app/views/compositionexplore/Compositionexplore.py", line 54, in <listcomp>
rqworker_1  |     a in allowed_combinations]
rqworker_1  |   File "/usr/local/lib/python3.6/site-packages/smact/properties.py", line 146, in compound_electroneg
rqworker_1  |     compelectroneg = (prod)**(1.0/(sum(stoichslist)))
rqworker_1  | ZeroDivisionError: float division by zero

**Comment by keeeto** [comment]
Thanks for pointing this out @usccolumbia - so just to clarify, the error here is with the code in the docs? If you run with a[2] then you get the correct solution?

**Comment by usccolumbia** [comment]
yes

Jianjun Hu
-----------------------------------------------------------------
Associate Professor, Graduate Recruiting Director
Department of Computer Science and Engineering
University of South Carolina
2223 Storey Innovation Center
550 Assembly Street, Columbia, SC, 29201
Lab page: http://mleg.cse.sc.edu<http://mleg.cse.sc.edu/>
Publication: Google Scholar link<https://scholar.google.com/citations?hl=en&user=_iD3nyMAAAAJ&view_op=list_works&sortby=pubdate>
Research Areas: AI&ML&DL for materials informatics, bioinformatics, health informatics, and intelligent manufacturing.

________________________________

**Comment by keeeto** [comment]
Thanks - I'll check that and update the docs.

**Comment by usccolumbia** [comment]
I got this correct results

formula,oxidation,electronegativity
Sr3TiO,1,-1,-2,3.6160059800904123
Sr4Ti2O,1,-1,-2,3.476656714707726
Sr2TiO,1,-1,-1,3.8298785309830863
Sr3TiO2,1,-1,-1,4.0871022645116
Sr3Ti2O,1,-1,-1,3.588843296006431
Sr4TiO3,1,-1,-1,4.2221217898177965
Sr4Ti3O,1,-1,-1,3.474075427539515
SrTiO,1,1,-2,4.214810953619044
SrTi3O2,1,1,-2,4.346510125033514
Sr2Ti4O3,1,1,-2,4.30215939643356
Sr3TiO2,1,1,-2,4.0871022645116
Sr4Ti2O3,1,1,-2,4.129235980766715
SrTiO2,1,1,-1,4.874391487357421
SrTi2O3,1,1,-1,4.94996017087597
SrTi3O4,1,1,-1,4.9881827177606315
Sr2TiO3,1,1,-1,4.799976474925424
Sr3TiO4,1,1,-1,4.763196080894375
Sr2TiO2,1,2,-2,4.385483338263423
Sr2Ti2O3,1,2,-2,4.5799360938001525
Sr2Ti3O4,1,2,-2,4.691666891920951
Sr4TiO3,1,2,-2,4.2221217898177965
SrTiO3,1,2,-1,5.318703623854412
Sr2TiO4,1,2,-1,5.119818538097441
SrTiO2,1,3,-2,4.874391487357421
Sr3TiO3,1,3,-2,4.460728231063388
SrTiO4,1,3,-1,5.6371905249086565
Sr2TiO3,1,4,-2,4.799976474925424
Sr4TiO4,1,4,-2,4.50308739279905
Sr2Ti2O,2,-1,-2,3.7520123113442816
Sr3Ti2O2,2,-1,-2,3.990346548038475
Sr3Ti4O,2,-1,-2,3.555176692884863
Sr4Ti2O3,2,-1,-2,4.129235980766715
SrTiO,2,-1,-1,4.214810953619044
Sr2TiO3,2,-1,-1,4.799976474925424
Sr2Ti3O,2,-1,-1,3.7009830084684063
Sr3Ti2O4,2,-1,-1,4.5964101244582105
Sr3Ti4O2,2,-1,-1,3.864892577844331
SrTi2O2,2,1,-2,4.550431489039785
SrTi4O3,2,1,-2,4.524770920972589
Sr2Ti2O3,2,1,-2,4.5799360938001525
Sr3Ti2O4,2,1,-2,4.5964101244582105
SrTiO3,2,1,-1,5.318703623854412
SrTi2O4,2,1,-1,5.256639835856972
SrTiO2,2,2,-2,4.874391487357421
SrTi2O3,2,2,-2,4.94996017087597
SrTi3O4,2,2,-2,4.9881827177606315
Sr2TiO3,2,2,-2,4.799976474925424
Sr3TiO4,2,2,-2,4.763196080894375
SrTiO4,2,2,-1,5.6371905249086565
SrTi2O4,2,3,-2,5.256639835856972
SrTiO3,2,4,-2,5.318703623854412
Sr2TiO4,2,4,-2,5.119818538097441


I do have one question about how to check electronegativity balance from your electronegativity calculation?

**Comment by keeeto** [comment]
Good that it works out! Can you expand on your question - I am not sure I follow exactly?
